name: Autograding
description: "Autograding for GoRace"
author: "@gorace-ull"
inputs:
  activity:
    description: The GoRace activity associated to the repsoitory.
    required: true
  assigmentId:
    description: The ID of the assigment in GH Classroom.
    required: true
  classroomId:
    description: The ID of the classroom in GH Classroom.
    required: true
  race:
    description: The name of the race in gh2gr server.
    required: true
  token:
    description: >
      GitHub token used to check repository content and provide feedback. By default, 
      this uses the repository token provided by GitHub Actions. You can customize this
      by replacing this token with a user token which has write-access to your repository. 
      Note that the token will be accessible to all repository collaborators.
    default: ${{ github.token }}
runs:
  using: "node20"
  main: "./dist/index.js"
